---
title: "Project Proposal"
author: "The BEST Fit - Olivia Encarcion, Leo Yang, Philip Lin, Allison Yang"
format: pdf
execute: 
  warning: false
editor: visual
---
#### Results

The final model we fit was:

$$
\begin{aligned}
\log\left( \frac{\pi}{1-\pi} \right) =\ & \beta_0 + \beta_1\ \text{kw avg avg} + \beta_2\ \log(\text{n tokens content} + 10^{-4}) + \beta_3\ \text{global subjectivity} + \beta_4\ \text{title sentiment polarity} \\
& + \left( \sum_{i=1}^{4} \beta_{4+i}\ \mathbf{1}\{\text{data channel} = \text{level}_i\} \right) \\
& + \left( \sum_{j=1}^{6} \beta_{8+j}\ \mathbf{1}\{\text{day published} = \text{level}_j\} \right) \\
& + \left( \sum_{i=1}^{4} \beta_{14+i}\ \log(\text{n tokens content} + 10^{-4})\ \mathbf{1}\{\text{data channel} = \text{level}_i\} \right) \\
& + \left( \sum_{i=1}^{4} \beta_{18+i}\ \text{global subjectivity}\ \mathbf{1}\{\text{data channel} = \text{level}_i\} \right)
\end{aligned}
$$

```{r}
#| fig.cap: "Confusion Matrix for the Interaction Model"
#| fig-width: 4
#| fig-height: 2
# Predict log-odds using the interaction model
log_odds_int <- predict(interactsMod, newdata = newsdf)
news_eval <- newsdf |>
  bind_cols(log_odds_int = log_odds_int)
# Convert to predicted probabilities
news_eval <- news_eval |>
  mutate(
    prob_int = exp(log_odds_int) / (1 + exp(log_odds_int))
  )
news_eval <- news_eval |>
  mutate(
    predicted_label = case_when(
      prob_int < 0.493 ~ 0,
      prob_int >= 0.493 ~ 1,
      TRUE ~ NA_real_
    ),
    predicted_label = as.factor(predicted_label),
    is_viral = as.factor(is_viral)
  )
conf_matrix_int <- news_eval |>
  conf_mat(is_viral, predicted_label)
autoplot(conf_matrix_int, type = "heatmap")
```

When evaluating our final model, we see it has an AUC of $\sim 0.697$%, an accuracy of $\sim 64.75%$%, specificity of $\sim 64.34%$%, and sensitivity of $\sim 65.03%$%. If we consider the misclassification rate of only $\sim 35.25%$, evaluation suggests that our model is moderately well-fit for the data. This precision means that $\sim64$% of articles predicted to be viral were correctly classified, indicating that the model performs substantially better than random chance.

If we assess the assumptions of logistic regression underlying our model, we see approximately linear relationships randomly dispersed around the trend line. Notably, vertical scatter of points around the trend line for subjectivity and title polarity presents a high degree of noise that might be impacting model performance.

Interpreting the coefficients of the model, we can conclude:

Article category, or 'Data Channel' the most strongly correlated with virality, with the odds of articles in the Social Media and Technology categories to go viral are approximately 15.66 times and 4.76 times that of a similar article in the Business category (reference group). Similarly, Entertainment and World news articles also show significantly higher odds of going viral than similar Business news articles, with odds ratios of 2.44 and 2.20, respectively. This suggests that readers are particularly engaged with content about social media and technology innovations, and also tend to share Entertainment and World news more than articles about Business news, however, not to the degree of Social Media and Technology articles. 

Day of publication is another important factor, with weekend publications significantly outperforming weekday content. Compared to Monday, Saturday articles have 2.81 times the odds , and Sunday articles have 2.47 times the odds of going viral, holding all else constant. In contrast, the odds of Tuesday and Wednesday articles going viral are 11.7% and 13.5% lower, with odds ratios of 0.883 and 0.865, respectively, than similar Monday articles. This weekend effect may arise from increased leisure time, as people take off from work or school during the weekend.

Article subjectivity and sentiment likely also influence virality. A fully subjective article (global subjectivity = 1) has 6.12 times the odds of going viral compared to a fully objective article (global subjectivity = 0), keeping all else constant. Similarly, a one-unit increase in title sentiment polarity (a neutral article compared to strongly positive) increases the odds of virality by 26.6%. This trend supports the idea that emotionally charged or opinionated content tends to be shared more frequently than neutral content. 

Keyword popularity also plays a role in determining the odds of an article going viral. Specifically, every time keyword popularity is doubled, the odds of an article going viral increase by about 29.1%, holding all else constant. While article length is a statistically significant predictor of an article’s virality, its impact is minimal. Specifically, every 10% increase in article length increases the odds of virality by approximately 1.55%, holding all else constant. Thus, while article length still adds to our model, it doesn’t add as much as predictors like day published or data channel.  


For Entertainment and World news, the benefit of article length is diminished or even reversed.  For Entertainment articles, every 10% increase in article length leads to a 1.9% decrease in the odds of going viral compared to a similar Business article, while for World news, a 10% increase in article length results in a 2.5% decrease in odds. The interaction terms between article length and Social Media or Technology is not statistically significant, suggesting the main effect of article length dominates in those categories.

In Social Media articles, a fully subjective tone actually reduces the odds of virality by 98.3%, despite the strong main effect of subjectivity. This suggests that objective tone may be more prone to virality for Social Media. In comparison, for Technology articles, subjectivity decreases odds by 82.6%. However, for both Entertainment and World news, these interaction effects are not statistically significant, which suggests that subjectivity could still hold a positive or neutral effect.

#### Discussion + Conclusion

Our findings support the idea that Article Length, Category, Keyword Popularity, Date of publication, subjectivity and title polarity all contribute to an online article's success, while other factors like the rate of positive/negative words were less reliable predictors. Through the empirical logit plot and the drop-in-deviance test of the interaciton terms, we determined that the effects of article length and global subjectivity both vary based on article topics.

Since the Mashable repository was collected over a multi-year time period, one limitation of our approach is the distinct possibility of outside temporal factors. This poses a potential violation of the independent observation assumption, with major events potentially shaping article performance on shorter time scales.

Another limitation to our findings are the poor interpretability of the NLP derived predictors, such as 'title-sentiment-polarity' and 'keyword average average', which were derived in an extensive process by the UCI researchers who curated the dataset.

Finally, our model only contains observations from Mashable, so extrapolation to other news/article sites may be limited.

To reduce the influence of these factors in future work, we might control for time period in the data and compare articles between different sites for better generalization. Beyond that, utilizing our own NLP metrics might give us finer grain control, allowing us to consider better predictors for our model.
