---
title: "Exploratory Data Analysis Written Report"
author: "The BEST Fit - Philip, Olivia, Leo, Allison"
date: "3/7/2025"
format: pdf
execute: 
  warning: false
  message: false
  echo: false
editor: visual
---

```{r}
#| label: load packages and data
 library(tidyverse)
 library(tidymodels)
 library(ggplot2)
 library(dplyr)

 newspopularity <- read_csv("data/OnlineNewsPopularity.csv")
```

Introduction:

Exploratory Data Analysis:

First, to we will convert the variables for day of the week and article topic into categorical variables for easier visualization.

```{r}
newspopularity$day_published <- NA  # Create a new empty column

newspopularity$day_published <- case_when(
  newspopularity$weekday_is_monday == 1 ~ "Monday",
  newspopularity$weekday_is_tuesday == 1 ~ "Tuesday",
  newspopularity$weekday_is_wednesday == 1 ~ "Wednesday",
  newspopularity$weekday_is_thursday == 1 ~ "Thursday",
  newspopularity$weekday_is_friday == 1 ~ "Friday",
  newspopularity$weekday_is_saturday == 1 ~ "Saturday",
  newspopularity$weekday_is_sunday == 1 ~ "Sunday",
)

newspopularity$day_published <- factor(
  newspopularity$day_published,
  levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
)


newspopularity$data_channel <- NA

newspopularity$data_channel <- case_when(
  newspopularity$data_channel_is_entertainment == 1 ~ "Entertainment",
  newspopularity$data_channel_is_bus == 1 ~ "Business",
  newspopularity$data_channel_is_socmed == 1 ~ "Social Media",
  newspopularity$data_channel_is_tech == 1 ~ "Technology",
  newspopularity$data_channel_is_world == 1 ~ "World",
)

newspopularity$data_channel <- factor(newspopularity$data_channel)
head(newspopularity)
```

```{r}
ggplot(newspopularity, aes(x = rate_positive_words)) +
  geom_histogram(binwidth = 0.02, fill = "green", color = "black") +
  labs(title = "Distribution of the prevalence of positive words",
       x = "Prevalence of positive words",
       y = "Frequency") + 
  theme_minimal()
```

```{r}
ggplot(newspopularity, aes(x = rate_negative_words)) +
  geom_histogram(binwidth = 0.02, fill = "red", color = "black") +
  labs(title = "Distribution of the prevalence of negative words",
       x = "Prevalence of negative words",
       y = "Frequency") + 
  theme_minimal()
```

```{r}
ggplot(newspopularity, aes(x = title_sentiment_polarity)) +
  geom_histogram(binwidth = 0.02, fill = "blue", color = "black") +
  labs(title = "Distribution of the polarities of the title",
       x = "Degree of polarity of the title",
       y = "Frequency") + 
  theme_minimal()
```

```{r}
ggplot(newspopularity, aes(x = n_tokens_content)) +
  geom_histogram(binwidth = 100, fill = "purple", color = "black") +
  labs(title = "Distribution of the length of article content",
       x = "Article Length",
       y = "Frequency") + 
  theme_minimal()
```

```{r}
ggplot(newspopularity, aes(x = n_tokens_title)) +
  geom_histogram(binwidth = 1, fill = "pink", color = "black") +
  labs(title = "Distribution of the length of title",
       x = "Title length",
       y = "Frequency") + 
  theme_minimal()
```
